name: "Prepare Node Env"
description: "start node env with pnpm"

runs:
    using: composite
    steps:
        -   uses: pnpm/action-setup@v2
            with:
                version: 8
                run_install: false

        -   uses: actions/setup-node@v3
            with:
                node-version: "18.18"
                cache: "pnpm"

        -   name: Install deps
            shell: bash
            run: pnpm install --frozen-lockfile
