name: Uploady Storybook Publish

on:
    workflow_dispatch

defaults:
    run:
        shell: bash

jobs:
    publish:
        name: Publish Uploady Storybook
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3

            -   name: Prepare
                uses: ./.github/actions/prepare

            -   name: Build Storybook Site
                run: pnpm sb:build:prod

            -   name: Install Netlify CLI
                run: pnpm install -w netlify-cli

            -   name: Publish Storybook to Netlify
                uses: jsmrcaga/action-netlify-deploy@v2.0.0
                with:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
                  NETLIFY_DEPLOY_MESSAGE: "Deployed from GitHub action"
                  NETLIFY_DEPLOY_TO_PROD: true
                  install_command: "echo Skipping installing the dependencies"
                  build_command: "echo Skipping building the web files"

